# Generated by Django 5.2 on 2025-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('map_iframe', models.TextField(help_text='Google Maps embed iframe kodu')),
            ],
            options={
                'verbose_name': 'İletişim Ayarları',
                'verbose_name_plural': 'İletişim Ayarları',
            },
        ),
    ]
