# Generated by Django 5.2 on 2025-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactsettings',
            options={'verbose_name': 'İletişim Ayarı', 'verbose_name_plural': 'İletişim Ayarları'},
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='map_iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
