# Generated by Django 5.2 on 2025-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(choices=[('Çim Serimi', 'Çim Serimi'), ('Villa / Site Peyzajı', 'Villa / Site Peyzajı'), ('Ağaç Ve Çalıların Dikimi', 'Ağaç Ve Çalıların Dikimi'), ('Otomatik Sulama & Drenaj ', 'Otomatik Sulama & Drenaj'), ('Sert Zemin & Yapısal Peyzaj', 'Sert Zemin & Yapısal Peyzaj'), ('Peyzaj Tasarım ve Uygulamaları', 'Peyzaj Tasarım ve Uygulamaları'), ('Toprak Dolgusu ', 'Toprak Dolgusu'), ('Diğer', 'Diğer')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
